#!/bin/bash


./trainFetchHTML.sh > trains.html



count=$1
x=2

for (( c=0; c<count; c++  ))
do
	cat trains.html | ./getNextTrain.sh $x > nextTrain

        trainName=`cat nextTrain | ./getTrainName.sh`
        trainNumber=`cat nextTrain | ./getTrainNo.sh`
        arrivalTime=`cat nextTrain | ./getArrivalTime.sh`
        journeyDate=`date "+%d-%b-%Y"`

       ./nextTrainStatus $trainNumber $journeyDate  > nextTrainStatus.html

        trainStatus=`cat nextTrainStatus.html | ./getTrainStatus.sh`


        printf "\n"
        echo "Train Name    :$trainName"
        echo "Train No.     :$trainNumber"
        echo "Arrival Time  :$arrivalTime"
        echo "Status        :$trainStatus"

	((x++));
done



